version: "2"
services:
  influxdb:
    restart: unless-stopped
    container_name: influxdb
    image: "influxdb:1.7-alpine"
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: "canopus"
      INFLUXDB_ADMIN_USER: "user"
      INFLUXDB_ADMIN_PASSWORD: "admin"
    volumes:
      - "influxdb-data:/var/lib/influxdb"
#  monitor_os:
#    restart: unless-stopped
#    container_name: monitor_os
#    build:
#      context: ./monitor
#      dockerfile: Dockerfile

volumes:
  influxdb-data: { }